"""
{{PLUGIN_NAME_HUMAN}} -- MCP server stub.

{{DESCRIPTION}}

External services this server is meant to wrap:
{{MCP_SERVICES_LIST}}

Generated by PluginForge. Replace the TODO tool with real ones.

Run standalone for testing:
    python server.py

In normal use, Claude Code starts this server automatically via .mcp.json.
"""

from __future__ import annotations

import os
import sys

try:
    from mcp.server.fastmcp import FastMCP
except ImportError:
    sys.stderr.write(
        "ERROR: the `mcp` package is not installed.\n"
        "Run: pip install -r requirements.txt\n"
    )
    sys.exit(1)


# -----------------------------------------------------------------------------
# Server
# -----------------------------------------------------------------------------

mcp = FastMCP("{{PLUGIN_NAME}}-server")


# -----------------------------------------------------------------------------
# Tools
# -----------------------------------------------------------------------------

@mcp.tool()
def ping() -> str:
    """Health check. Returns 'pong'. Use to confirm the server is reachable."""
    return "pong"


@mcp.tool()
def echo(text: str) -> str:
    """Echo the input string back. Useful for debugging tool wiring."""
    return text


# TODO: replace these stubs with real tools. One example per external service.
#
# Example pattern (uncomment, adapt):
#
# import httpx
#
# @mcp.tool()
# def fetch_weather(city: str) -> dict:
#     """Fetch current weather for a city via OpenWeather."""
#     api_key = os.environ.get("OPENWEATHER_API_KEY")
#     if not api_key:
#         return {"error": "OPENWEATHER_API_KEY not set"}
#     url = "https://api.openweathermap.org/data/2.5/weather"
#     resp = httpx.get(url, params={"q": city, "appid": api_key, "units": "metric"})
#     resp.raise_for_status()
#     return resp.json()


# -----------------------------------------------------------------------------
# Entrypoint
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    # FastMCP speaks stdio by default; this is what Claude Code expects.
    mcp.run()
